// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function GetLocalIPs():Promise<Array<main.IPInfo>>;

export function GetLogs():Promise<Array<string>>;

export function SelectDirectory():Promise<string>;

export function StartServer(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: any}>;

export function StopServer():Promise<{[key: string]: any}>;
