// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
